POST http://localhost:3333/equipments
Content-Type: application/json

{
  "publicId": "pub-001",
  "name": "Carnes",
  "modelo": "Freezer 500L",
  "numSerie": "RF-2024-001",
  "marca": "CoolTech",
  "loja": "Loja Central",
  "setor": "açougue",
  "endereco": "Rua do Helder câmera, - recife PE",
  "compressor": "Danffos - MT-100",
  "controlador": "TC-900E POWER",
  "refrigerante": "R-134a",
  "status": "operacional",
  "observacoes": "Primeira instalação feita em 2024"
}

###

GET http://localhost:3333/equipments?search=